version: "3.8"
services:

  discovery-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  discovery-service:
    build: ./discovery
    container_name: discovery-service
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: discovery-redis
      REDIS_PORT: 6379
    depends_on:
      - discovery-redis

  # statussphere-mongodb:
  #     image: mongodb:latest
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - mongodb-data:/data/db
  #     environment:
  #       MONGO_ROOT_USERNAME: myrootuser
  #       MONGO_ROOT_PASSWORD: myrootpassword

  #   statussphere:
  #     build: ./statussphere
  #     ports:
  #       - "4040:4040"
  #     environment:
  #       REDIS_HOST: discovery-redis
  #       REDIS_PORT: 6379
  #     volumes:
  #       - redis-data:/data
  #     depends_on:
  #       - statussphere-mongodb



  # Matchmaker Service
  # matchmaker:
  #   build: ./matchmaker
  #   ports:
  #     - "6060:6060"
  #   environment:
  #     RABBITMQ_HOST: rabbitMQ
  #     RABBITMQ_PORT: 5672
  #   depends_on:
  #     - rabbitMQ

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitMQ-data:/var/lib/rabbitmq
      - rabbitMQ-config:/etc/rabbitmq

  drivermaster-postgres:
    image: postgres
    container_name: drivermaster-postgres
    environment:
      POSTGRES_DB: driverdb
      POSTGRES_USER: driverService
      POSTGRES_PASSWORD: driver
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  drivermaster:
    build: ./drivermaster
    container_name: drivermaster
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: driverdb
      POSTGRES_USER: driverService
      POSTGRES_PASSWORD: driver
    ports:
      - "7070:80"
    depends_on:
      - drivermaster-postgres

volumes:
  mongo-data:
  postgres-data:
  rabbitMQ-data:
  rabbitMQ-config:
  redis-data:
    driver: local
