# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 7070

# Define environment variable for Flask (optional)
# ENV FLASK_APP=your_app_file.py

# Run app.py when the container launches
CMD ["python", "driver.py"]
