apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubectl\kompose.exe convert -o .\artifects\
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tripguard
  name: tripguard
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tripguard
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubectl\kompose.exe convert -o .\artifects\
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tripguard
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: mysql-tripguard
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: tripguard
          name: tripguard
          ports:
            - containerPort: 4400
          resources: {}
      restartPolicy: Always
status: {}
