apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubectl\kompose.exe convert -f .\docker-compose.yml -o .\artifacts\
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubectl\kompose.exe convert -f .\docker-compose.yml -o .\artifacts\
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: discovery
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: discovery-redis
            - name: REDIS_PORT
              value: "6379"
          image: imrraaj/discovery:latest
          name: discovery
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
