apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubectl\kompose.exe convert -f .\docker-compose.yml -o .\artifacts\
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: matchmaker
  name: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: matchmaker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubectl\kompose.exe convert -f .\docker-compose.yml -o .\artifacts\
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: matchmaker
    spec:
      containers:
        - env:
            - name: DRIVEMASTER_SERVICE
              value: drivermaster
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: TRANSITEDGE_SERVICE
              value: transitedge
          image: imrraaj/matchmaker:latest
          name: matchmaker
          ports:
            - containerPort: 6060
          resources: {}
      restartPolicy: Always
status: {}
